baseURL = 'https://phylly.com/'
languageCode = 'en-us'
title = 'Phylly'
theme = 'PaperMod'
[pagination]
  pagerSize = 5

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Welcome to Phylly"
    Content = ""

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 5
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false
